device: 'cuda'
batch_size: 64
num_classes: 431
data_dir: '../data/CompCars/web_nature'
use_bbox_train: False  # for MyDataset class
use_bbox_val: False  # for MyDataset class
model_no: 1
use_my_model: True
aux_logits: False  # For Inceptionv3 only
use_dp: True  # For data parallel ops, change gpu id in code below
dp_gpu_id: [0, 1]
model_path: 'mymodel.pth'  # Path to model's state_dict
